lifecycle=[
'Study proposal',
'Funding',
'Study design',
'Instrument design',
'Questionnaire translation',
'Questionnaire adaptation',
'Interviewer training',
'Ethics review',
'Legal review',
'Sampling',
'Instrument pre-testing',
'Pilot study',
'Data collection',
'Data collection reports',
'Data processing',
'Data processing: Coding',
'Data processing: Classification',
'Data processing: Transcriptions of interviews',
'Data processing: Weighting',
'Data processing: Aggregation',
'Data processing: Composite measures',
'Data processing: Derivation',
'Data processing: Quality checks',
'Data processing: Data integration',
'Data processing: Disclosure limitation',
'Data processing: Imputation',
'Metadata production',
'Metadata editing',
'Metadata translation',
'Final report',
'Evaluation',
'Original release',
'Deposit',
'Preservation package production',
'Dissemination package production',
'Dissemination package release',
'Data analysis reports',
'New version release',
'Other'
]