var chkbxdico =
{multivalorisation: ["Articles dans d'autres revues",
                       "Articles dans des revues du WOS",
                       "Brevets",
                       "Communiqués de presse",
                       "Logiciels ou bases de données",
                       "Ouvrages ou chapitres",
                       "Publications de transfert ou guides techniques",
                       "Thèses",
                       "Vulgarisation scientifique"],
 tag_annee: ["1990",
               "1991",
               "1992",
               "1993",
               "1994",
               "1995",
               "1996",
               "1997",
               "1998",
               "1999",
               "2000",
               "2001",
               "2002",
               "2003",
               "2004",
               "2005",
               "2006",
               "2007",
               "2008",
               "2009",
               "2010",
               "2011",
               "2012",
               "2013",
               "2014",
               "2015",
               "2016",
               "2017",
               "2018",
               "2019",
               "2020",
               "2021",
               "2022",
               "2023",
               "2024",
               "2025"],
 tag_autredonnee: ["GPS", "Photo", "Vidéo", "dendrochronologie"],
 tag_contrat: ["B4EST", "CIRAD ATP 2007/1", "Clonix2D", "EPITREE", "EVOLTREE", "EquipEx Xyloforest", "GENOAK", "HOMED", "LABEX RESCUE", "LVMH Projet FAUX", "TREEMUTATION", "TREEPEACE"],
 tag_dispo: ["ABIOGEN",
               "Bercé_Réno-Valdieu_Tronçais",
               "CASTILLONVILLE GENET",
               "CLONAPIN",
               "Ciron",
               "Collection des clones de châtaigniers",
               "Dispositif QTL pin maritime",
               "Faux de Verzy",
               "Forêt Guyanaise",
               "Gradients altitudinaux Aquitaine-Pyrénées",
               "ORPHEE",
               "Phytoremédiation",
               "Tests de provenances et descendances de chênes et hêtre"],
 tag_dna: ["Cartes génétiques", "Epigénétique", "GWAS", "Génome", "Marqueurs", "Métabolome", "QTL", "Transcriptome"],
 tag_dynamique: ["Spatiale", "Temporelle"],
 tag_envt: ["Climat", "Sol"],
 tag_espece: ["Castanea sativa",
                "Dicorynia guianensis",
                "Erysiphe alphitoides",
                "Erysiphe quercicola",
                "Fagus sylvatica",
                "Picea abies",
                "Pinus nigra",
                "Pinus pinaster",
                "Pinus sylvestris",
                "Populus deltoides",
                "Populus nigra",
                "Populus trichocarpa",
                "Quercus petraea",
                "Quercus robur",
                "Quercus suber",
                "Sextonia rubra"],
 tag_financeur: ["ANR", "Agence de l'Eau Bassin Adour Garonne", "ERC", "European community BIODIVERSA/0002/2012", "Horizon 2020", "INRA", "INRAE", "LVMH", "Labex CEBA", "Labex COTE", "ONF", "Région Nouvelle-Aquitaine"],
 tag_habitat: ["Forêt tempérée", "Forêt tropicale", "Montagne", "Prairie", "Zone contrôlée", "Zone dunaire", "Zone humide", "Zone urbaine"],
 tag_info: ["Analyses / Statistiques", "BDD", "Programme", "Scripts", "Simulation / Modélisation"],
 tag_nvxbio: ["1_molécule", "2_cellule", "3_tissu", "4_organe", "5_individu", "6_population", "7_espèce", "8_communaut&eacute;"],
 tag_organisme: ["Algues", "Arachnides", "Arbres", "Bactéries", "Champignons", "Grands mammifères", "Oiseaux", "Plantes herbacées", "Virus"],
 tag_pheno: ["Architecture", "Biodiversité", "Biomasse", "Bois", "Croissance", "Germination", "Herbivorie", "Métabolites", "Phénologie", "Port (botanique)", "Prédation"],
 tag_site: ["Allemagne",
              "Bercé",
              "Bois des Sources",
              "Bourran",
              "Castillonville",
              "Clermont-Ferrand (Nebouzat)",
              "Clermont-Ferrand (Orcine)",
              "Domaine de l'Hermitage",
              "Forêt de Verzy",
              "Ile de Raymond",
              "Le Rousset",
              "Paracou",
              "Réno-Valdieu",
              "Saint-Gengoux-de-Scissé",
              "Sionne",
              "Tronçais",
              "Vallée du Ciron",
              "route Regina St Georges PK152"]};
var listdico =
{diffusion: ["Mixte", "Privé", "Public"],
 organism: ["INRA", "INRAE", "INRAe Biogeco"],
 organismtech: ["CNRGV", "Génoscope - CEA", "INRA", "INRAE", "INRAe Biogeco", "ONF"],
 statutdispo: ["Disponible brut", "Disponible exploitable", "En cours"]};
