<footer class="footer">
   <hr>
   <table width="100%"><tr>
   <td align="left"><a href="<?php echo $PATH ?>"><img src="<?php echo $PATH ?>img/logo2.svg" width="12%"></a></td>
   <td align="right"><a href="https://www.inrae.fr/en" target="_blank"><img src="<?php echo $PATH ?>img/logo_inrae.svg"  width="50%"></a><br><span class="footer_cpr">&copy; <? echo $YEAR ?></span></td>
   </tr></table>
</footer>

</body>
</html>
