<?php

$ZENODO['GRANTS_DOI'] = [ 
	'EU' => '10.13039/501100000780',
	'ANR' => '10.13039/501100001665'
];

$ZENODO['ACCESS_RIGHTS'] = [
	'Public' => 'open',
	'Private' => 'closed',
	'Mixte' => 'restricted'
];

$ZENODO['RELATION_TYPES'] = [
	"Audiovisual" => "video", 
	"Book" => "publication", 
	"BookChapter" => "publication", 
	"Collection" => "dataset", 
	"ComputationalNotebook" => "other", 
	"ConferencePaper" => "presentation", 
	"ConferenceProceeding" => "presentation", 
	"DataPaper" => "publication", 
	"Dataset" => "dataset", 
	"Dissertation" => "publication", 
	"Event" => "other", 
	"Image" => "image", 
	"InteractiveResource" => "other", 
	"Journal" => "publication", 
	"JournalArticle" => "publication", 
	"Model" => "other", 
	"Other" => "other", 
	"OutputManagementPlan" => "other", 
	"PeerReview" => "publication", 
	"PhysicalObject" => "physicalobject", 
	"Preprint" => "publication", 
	"Report" => "publication", 
	"Service" => "other", 
	"Software" => "software", 
	"Sound" => "other", 
	"Standard" => "other", 
	"Text" => "other", 
	"Workflow" => "other"
];

?>
